TodoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
]

tasks/urls.py
from django.urls import path

from .views import (
    index,
    TagCreateView,
    TagListView,
    TagUpdateView,
    TagDeleteView,

    TaskCreateView,
    task_toggle,
    TaskUpdateView,
    TaskDeleteView,
)

urlpatterns = [
    path("",
         index,
         name="index", ),
    path("tags/create/",
         TagCreateView.as_view(),
         name="tag-create", ),
    path("tags/",
         TagListView.as_view(),
         name="tag-list", ),
    path("tags/<int:pk>/update/",
         TagUpdateView.as_view(),
         name="tag-update", ),
    path("tags/<int:pk>/delete/",
         TagDeleteView.as_view(),
         name="tag-delete", ),
    path("tasks/create/",
         TaskCreateView.as_view(),
         name="task-create", ),
    path('task/<int:pk>/toggle/',
         task_toggle,
         name='task-toggle'),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
]

app_name = "tasks"

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50, )

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True, )
    deadline_datetime = models.DateTimeField(null=True,
                                             blank=True, )
    is_done = models.BooleanField(default=False, )
    tags = models.ManyToManyField(Tag,
                                  related_name="tasks", )

    def __str__(self):
        return self.content[:50]

tasks/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from tasks.models import Tag, Task


def index(request):
    return render(request, "tasks/index.html",
                  {'tasks': Task.objects.prefetch_related(
                      'tags').order_by('is_done', '-created_datetime')})


def task_toggle(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return HttpResponseRedirect(reverse('tasks:index'))


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagListView(generic.ListView):
    model = Tag

    def get_queryset(self):
        return Tag.objects.prefetch_related(
            "tasks__tags",
        )


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "tasks/delete_tag.html"
    success_url = reverse_lazy("tasks:tag-list")


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "tasks/delete_task.html"
    success_url = reverse_lazy("tasks:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <title>Movie Top</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/delete_tag.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/delete_task.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete  Task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <h1>TODO list</h1>
    </div>
    <div class="col-auto">
      <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page">Add task</a>
    </div>
  </div>
  {% if tasks %}
    {% for task in tasks %}
      {{ task.content }}
      {% if task.is_done %}
        <span class="text-success">Done</span>
        <form action="{% url 'tasks:task-toggle' pk=task.pk %}" method="post" style="display: inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-warning">Undo</button>
        </form>
      {% else %}
        <span class="text-danger">Not done</span>
        <form action="{% url 'tasks:task-toggle' pk=task.pk %}" method="post" style="display: inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-success">Complete</button>
        </form>
      {% endif %}
      <br>Created : {{ task.created_datetime }}<br>
      <p>Tags:
        {% for tag in task.tags.all %}
          {{ tag }}
          <a href="{% url 'tasks:tag-update' pk=tag.id %}" class="text-success">
            Update
          </a>
          <a href="{% url 'tasks:tag-delete' pk=tag.id %}" class="text-danger">
            Delete
          </a></p>
          <hr class="my-3">
        {% endfor %}
    {% endfor %}
  {% else %}
    <p>No tasks available</p>
  {% endif %}
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block title %}<title>Tags</title>{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
        <h1>Tags</h1>
    </div>
    <div class="col-auto">
        <a href="{% url 'tasks:tag-create' %}" class="btn btn-primary link-to-page">Add</a>
    </div>
</div>
  {% if tag_list %}
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      </thead>
      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'tasks:tag-update' pk=tag.id %}" class="btn btn-primary link-to-page">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'tasks:tag-delete' pk=tag.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}

{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}